spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ers?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8090
